# Generated by Django 3.0.3 on 2020-03-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xyz',
            name='Type',
        ),
        migrations.AddField(
            model_name='xyz',
            name='credit',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='xyz',
            name='debit',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='xyz',
            name='name',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
