# Generated by Django 3.0.3 on 2020-03-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0002_auto_20200308_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xyz',
            name='credit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='xyz',
            name='debit',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
