# Generated by Django 3.0.3 on 2020-03-10 06:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0003_auto_20200310_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='xyz',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='xyz',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
